FROM python:3.10-slim

WORKDIR /app

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy function code
COPY ./src/data_crawling /app/data_crawling
COPY ./src/core /app/core

# # Set the CMD to your handler
CMD ["python", "-m", "data_crawling.main"]
